<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>CredentialProvider.Gen2Support</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NLog" Version="6.1.4" />
		<PackageReference Include="NuGet.Credentials" Version="7.6.0" />
		<PackageReference Include="NuGet.Protocol" Version="7.6.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="_NLog.config">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
